name: 🔬 Pull Request Checks
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗️ Run build
        run: npm run build

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: npm run typecheck

  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint
        run: npm run lint

  package:
    name: 📦 Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗️ Run build
        run: npm run build

      - name: 📦 Lint Package
        run: npm run lint:package

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: ⚡ Run vitest
        run: npm run test
